### ISSUE TITLE
Preview PDF for PDF only submission returns status 500

### ISSUE THREAD

**Issue by erickpeirson** [arXiv/arxiv-submission-ui#85]
![Screenshot_20190604-200517](https://user-images.githubusercontent.com/3451594/58921393-768bc080-8704-11e9-8119-9a1fde93f8c8.png)

**Comment by erickpeirson** [comment]
Looks like it's hitting the classifier, rather than loading from filemanager:

```
[2019-06-04 20:59:31,466] ERROR in app: Exception on /2715270/preview.pdf [GET]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/arxiv/users/auth/decorators.py", line 242, in wrapper
    return func(*args, **kwargs)
  File "./submit/routes/ui.py", line 410, in file_preview
    request.environ['token']
  File "./submit/controllers/process.py", line 308, in file_preview
    submission.source_content.checksum, token)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/arxiv/submission/services/compiler/compiler.py", line 197, in get_product
    response = self.request('get', endpoint, token, stream=True)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/arxiv/integration/api/service.py", line 193, in request
    self._check_status(resp, expected_code)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/arxiv/integration/api/service.py", line 159, in _check_status
    raise_for_http_status(resp.status_code, resp)
  File "/root/.local/share/virtualenvs/arxiv-AI0WzCV4/lib/python3.6/site-packages/arxiv/integration/api/service.py", line 290, in raise_for_http_status
    raise NotFound(f'No such resource: {resp.url}', resp)
arxiv.integration.api.exceptions.NotFound: No such resource: http://xxx.xxx.xxx.xxx:80/9/Jilb2mB9Ky28By7OmkboVg==/pdf/product
```

**Comment by erickpeirson** [comment]
Cross-ref: [ARXIVNG-2217]

[ARXIVNG-2217]: https://arxiv-org.atlassian.net/browse/ARXIVNG-2217

**Comment by bdc34** [comment]
Work for this is in https://github.com/arXiv/arxiv-submission-ui/pull/128
